# -*- coding: utf-8 -*-
"""
/***************************************************************************
 XrasterPlug
                                 A QGIS plugin
 Multidimensional raster GIS
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2024-08-25
        copyright            : (C) 2024 by IO PAN
        email                : jackurbanski@iopan.pl
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load XrasterPlug class from file XrasterPlug.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .xraster_gis import XrasterPlug
    return XrasterPlug(iface)
